[package]
name = "payment_mandate"
version = "0.1.0"
edition = "2023_11"

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = ">=2.6.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.14.0" }